remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

theme: jekyll-theme-minimal
title: Typetta
logo: /assets/logo.png
description: Typescript fully typed ORM for SQL and MongoDB.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal