name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://npm.pkg.github.com
          scope: '@twinlogix'
      - name: Update npm
        run: npm install -g npm@7
      - name: Node verision
        run: node --version && npm --version
      - name: Installing node packages
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.PRIVATE_PACKAGES_TOKEN}}
      - name: Building
        run: npm run build
      - name: Test code generation
        run: npm run generate
      - name: Testing
        run: npm run test
